# Generated by Django 6.0.4 on 2026-04-24 09:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_area', models.CharField(max_length=150)),
                ('keterangan', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area Kerja',
                'verbose_name_plural': 'Area Kerja',
                'ordering': ['perusahaan', 'nama_area'],
            },
        ),
        migrations.CreateModel(
            name='JenisJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jasa', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Jasa',
                'verbose_name_plural': 'Jenis Jasa',
                'ordering': ['nama_jasa'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('kepala_supervisor', 'Kepala Supervisor'), ('supervisor', 'Supervisor Lapangan'), ('staff', 'Staff Lapangan'), ('customer', 'Customer')], default='staff', max_length=30)),
                ('nama_lengkap', models.CharField(blank=True, max_length=150)),
                ('telepon', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Nomor telepon hanya boleh berisi angka, dan opsional diawali dengan +. Panjang 7–20 karakter.', regex='^\\+?[0-9]{7,20}$')])),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='foto_profil/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'ordering': ['nama_lengkap'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perusahaan_customer', to=settings.AUTH_USER_MODEL)),
                ('jenis_jasa', models.ManyToManyField(blank=True, related_name='perusahaan', to='outsourcing.jenisjasa')),
            ],
            options={
                'verbose_name': 'Perusahaan',
                'verbose_name_plural': 'Perusahaan',
                'ordering': ['nama_perusahaan'],
            },
        ),
        migrations.CreateModel(
            name='LaporanKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_laporan', models.CharField(max_length=200)),
                ('tanggal_laporan', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('selesai', 'Selesai'), ('dikirim_customer', 'Dikirim ke Customer')], default='draft', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_kegiatan', to='outsourcing.areakerja')),
                ('jenis_jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_kegiatan', to='outsourcing.jenisjasa')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='laporan_yang_dibuat', to=settings.AUTH_USER_MODEL)),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_kegiatan', to='outsourcing.perusahaan')),
            ],
            options={
                'verbose_name': 'Laporan Kegiatan',
                'verbose_name_plural': 'Laporan Kegiatan',
                'ordering': ['-tanggal_laporan', 'perusahaan'],
            },
        ),
        migrations.AddField(
            model_name='areakerja',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_kerja', to='outsourcing.perusahaan'),
        ),
        migrations.CreateModel(
            name='StaffSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_saya', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_dibawahnya', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff per Supervisor',
                'verbose_name_plural': 'Staff per Supervisor',
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sub_area', models.CharField(max_length=150)),
                ('keterangan', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_area', to='outsourcing.areakerja')),
            ],
            options={
                'verbose_name': 'Sub Area',
                'verbose_name_plural': 'Sub Area',
                'ordering': ['area', 'nama_sub_area'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorPerusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('jenis_jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_perusahaan', to='outsourcing.jenisjasa')),
                ('kepala_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'kepala_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_dibawahnya', to=settings.AUTH_USER_MODEL)),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_perusahaan', to='outsourcing.perusahaan')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='penugasan_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penugasan Supervisor',
                'verbose_name_plural': 'Penugasan Supervisor',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_task', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('jenis_jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='outsourcing.jenisjasa')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task',
                'ordering': ['jenis_jasa', 'nama_task'],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_saya', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_yang_bisa', to='outsourcing.task')),
            ],
            options={
                'verbose_name': 'Staff Task',
                'verbose_name_plural': 'Staff Task',
            },
        ),
        migrations.CreateModel(
            name='ItemKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField(blank=True, null=True)),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('terjadwal', 'Terjadwal'), ('on_progress', 'On Progress'), ('selesai', 'Selesai')], default='terjadwal', max_length=20)),
                ('foto_on_progress', models.ImageField(blank=True, null=True, upload_to='foto_item/on_progress/')),
                ('foto_after', models.ImageField(blank=True, null=True, upload_to='foto_item/after/')),
                ('is_insidental', models.BooleanField(default=False, help_text='True jika pekerjaan ini dibuat oleh staff di luar jadwal.')),
                ('catatan_staff', models.TextField(blank=True, help_text='Catatan tambahan dari staff lapangan.')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('staff', models.ManyToManyField(limit_choices_to={'role': 'staff'}, related_name='item_kegiatan_saya', to=settings.AUTH_USER_MODEL)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_kegiatan', to='outsourcing.laporankegiatan')),
                ('sub_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_kegiatan', to='outsourcing.subarea')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_kegiatan', to='outsourcing.task')),
            ],
            options={
                'verbose_name': 'Item Kegiatan',
                'verbose_name_plural': 'Item Kegiatan',
                'ordering': ['tanggal', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='KepalaSupervisorJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('jenis_jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kepala_supervisor', to='outsourcing.jenisjasa')),
                ('kepala_supervisor', models.ForeignKey(limit_choices_to={'role': 'kepala_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='jasa_yang_dipegang', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kepala Supervisor Jasa',
                'verbose_name_plural': 'Kepala Supervisor Jasa',
                'unique_together': {('kepala_supervisor', 'jenis_jasa')},
            },
        ),
        migrations.AddIndex(
            model_name='laporankegiatan',
            index=models.Index(fields=['status'], name='idx_laporan_status'),
        ),
        migrations.AddIndex(
            model_name='laporankegiatan',
            index=models.Index(fields=['perusahaan', 'tanggal_laporan'], name='idx_laporan_perusahaan_tgl'),
        ),
        migrations.AddIndex(
            model_name='laporankegiatan',
            index=models.Index(fields=['supervisor', 'status'], name='idx_laporan_supervisor_status'),
        ),
        migrations.AlterUniqueTogether(
            name='areakerja',
            unique_together={('perusahaan', 'nama_area')},
        ),
        migrations.AlterUniqueTogether(
            name='staffsupervisor',
            unique_together={('staff', 'supervisor')},
        ),
        migrations.AlterUniqueTogether(
            name='subarea',
            unique_together={('area', 'nama_sub_area')},
        ),
        migrations.AlterUniqueTogether(
            name='supervisorperusahaan',
            unique_together={('supervisor', 'perusahaan', 'jenis_jasa')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('jenis_jasa', 'nama_task')},
        ),
        migrations.AlterUniqueTogether(
            name='stafftask',
            unique_together={('staff', 'task')},
        ),
        migrations.AddIndex(
            model_name='itemkegiatan',
            index=models.Index(fields=['tanggal', 'status'], name='idx_item_tanggal_status'),
        ),
        migrations.AddIndex(
            model_name='itemkegiatan',
            index=models.Index(fields=['laporan', 'status'], name='idx_item_laporan_status'),
        ),
    ]
