# Generated by Django 6.0.4 on 2026-05-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='status_harian',
            field=models.CharField(blank=True, choices=[('P', 'Hadir'), ('L', 'Cuti'), ('I', 'Izin'), ('A', 'Alpa'), ('DC', 'Surat Dokter'), ('LB', 'Libur')], default='P', max_length=5),
        ),
    ]
