# Generated by Django 6.0.4 on 2026-04-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporankegiatan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai'), ('dikirim_customer', 'Dikirim ke Customer')], default='draft', max_length=20),
        ),
    ]
