# Generated by Django 6.0.4 on 2026-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0002_absensi_status_harian'),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaan',
            name='foto_perusahaan',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perusahaan/'),
        ),
    ]
