# Generated by Django 6.0.4 on 2026-05-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0003_perusahaan_foto_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('l', 'Laki-laki'), ('p', 'Perempuan')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nik',
            field=models.CharField(blank=True, help_text='NIK / ID Karyawan (contoh: 202403157)', max_length=20, null=True, unique=True),
        ),
    ]
