# Generated by Django 6.0.4 on 2026-05-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0004_user_jenis_kelamin_user_nik'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheMetaLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('bulan', models.IntegerField()),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('fetch_sukses', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cache Meta Libur',
                'unique_together': {('tahun', 'bulan')},
            },
        ),
        migrations.CreateModel(
            name='HariLiburNasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True)),
                ('nama_libur', models.CharField(max_length=200)),
                ('tahun', models.IntegerField(db_index=True)),
                ('bulan', models.IntegerField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hari Libur Nasional',
                'verbose_name_plural': 'Hari Libur Nasional',
                'ordering': ['tanggal'],
                'indexes': [models.Index(fields=['tahun', 'bulan'], name='idx_libur_tahun_bulan')],
            },
        ),
    ]
