# Generated by Django 6.0.4 on 2026-05-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0005_cachemetalibur_hariliburnasional'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='izin_pulang_awal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absensi',
            name='keterangan_izin_pulang',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status',
            field=models.CharField(choices=[('belum_absen', 'Belum Absen'), ('masuk', 'Masuk'), ('pulang', 'Pulang'), ('terlambat', 'Terlambat'), ('overtime', 'Overtime')], default='belum_absen', max_length=20),
        ),
    ]
