# Generated by Django 6.0.4 on 2026-05-11 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0006_absensi_izin_pulang_awal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absensi',
            name='overtime_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='overtime_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absensi',
            name='overtime_status',
            field=models.CharField(blank=True, choices=[('belum_review', 'Belum Direview'), ('paid', 'Dibayar'), ('unpaid', 'Tidak Dibayar')], default='belum_review', max_length=20),
        ),
    ]
