# Generated by Django 6.0.4 on 2026-05-12 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0007_absensi_is_overtime_absensi_overtime_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzinStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('sakit', 'Sakit'), ('cuti', 'Cuti'), ('keluarga', 'Urusan Keluarga'), ('lainnya', 'Lainnya')], max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('lampiran', models.FileField(blank=True, null=True, upload_to='izin/')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('catatan_supervisor', models.TextField(blank=True)),
                ('direview_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('direview_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='izin_reviews', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Izin Staff',
                'verbose_name_plural': 'Izin Staff',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
