# Generated by Django 5.2.1 on 2026-05-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0008_izinstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(blank=True, help_text='NIK / ID Karyawan (contoh: 202403157)', max_length=20, null=True),
        ),
    ]
