# Generated by Django 5.2.1 on 2026-05-22 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0009_alter_user_nik'),
    ]

    operations = [
        migrations.AddField(
            model_name='areakerja',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_kerja_saya', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffsupervisor',
            name='area_kerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anggota', to='outsourcing.areakerja'),
        ),
    ]
