# Generated by Django 5.2.1 on 2026-05-22 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0010_areakerja_supervisor_staffsupervisor_area_kerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporankegiatan',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_kegiatan', to='outsourcing.areakerja'),
        ),
    ]
