# Generated by Django 5.2.1 on 2026-05-22 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0011_alter_laporankegiatan_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_milik', to=settings.AUTH_USER_MODEL),
        ),
    ]
