# Generated by Django 5.2.1 on 2026-05-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0012_task_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarea',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subarea_milik', to=settings.AUTH_USER_MODEL),
        ),
    ]
