# Generated by Django 5.2.1 on 2026-05-22 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0013_subarea_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_area', to='outsourcing.areakerja'),
        ),
    ]
