# Generated by Django 5.2.1 on 2026-05-22 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0014_alter_subarea_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarea',
            name='perusahaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_area', to='outsourcing.perusahaan'),
        ),
    ]
