# Generated by Django 5.2.1 on 2026-05-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0015_subarea_perusahaan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('jenis_jasa', 'nama_task', 'supervisor')},
        ),
    ]
